---
services:

  authz:
    image: $AWS_ECR_REPOSITORY/authz
    build:
      context: ./authz
      dockerfile: Dockerfile
    networks:
      - froch
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/200"]
      interval: 10s
      timeout: 1s
      retries: 3

  lambda:
    image: $AWS_ECR_REPOSITORY/lambda
    build:
      context: ./lambda
      dockerfile: Dockerfile
    networks:
      - froch

  localstack:
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"                      # main localstack endpoint
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:5053:53"              # Expose DNS/tcp to host (on port 5053)
      - "127.0.0.1:5053:53/udp"          # Expose DNS/udp to host (on port 5053)
    environment:
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 1
      LAMBDA_IGNORE_ARCHITECTURE: 1
      LOCALSTACK_AUTH_TOKEN: $LOCALSTACK_AUTH_TOKEN
      PERSISTENCE: 1
    volumes:
      - ./.localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock # dind
      - ./tools/assets:/tmp/assets
      - ./tools/localstack/cloudfront:/tmp/cloudfront
      - ./tools/localstack/init:/etc/localstack/init/ready.d/
      - ./tools/localstack/lambda:/tmp/lambda
      - ./tools/scripts:/tmp/scripts
    networks:
      - froch

networks:
  froch:
    driver: bridge
