---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz
  labels:
    app: authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authz
  template:
    metadata:
      labels:
        app: authz
    spec:
      containers:
        - name: authz
          image: $AWS_ECR_REPOSITORY/authz
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "128m"
          livenessProbe:
            httpGet:
              path: /200
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /200
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 1
